sudo: required
addons:
  chrome: stable

# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="jaguar_serializer"
      dart: dev
    - stage: build
      script: ./tool/travis.sh build
      env: PKG="jaguar_serializer_cli"
      dart: dev
    - stage: analyzer
      script: ./tool/travis.sh dartanalyzer
      env: PKG="jaguar_serializer"
      dart: dev
    - stage: format
      script: ./tool/travis.sh dartfmt
      env: PKG="jaguar_serializer_cli"
      dart: dev
    - stage: analyzer
      script: ./tool/travis.sh dartanalyzer
      env: PKG="jaguar_serializer_cli"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="jaguar_serializer_cli"
      dart: dev

stages:
  - format
  - build
  - analyzer
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache