name: jaguar_serializer
version: 0.0.2
description: A simple console application.

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  intl:
  source_gen_help:
    git: https://github.com/Jaguar-dart/source_gen_help.git

dev_dependencies:
  test:
  mongo_dart:
