name: jaguar_serializer
version: 0.1.3
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

executables:
  serializer:

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  intl:
  source_gen_help:
    git: https://github.com/Jaguar-dart/source_gen_help.git

dev_dependencies:
  test:
  mongo_dart:
