name: jaguar_serializer
version: 2.1.14
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer
documentation:

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  date_format: ^1.0.4

dev_dependencies:
  build_runner: ^0.9.0
  jaguar_serializer_cli:
    path: ../jaguar_serializer_cli