name: jaguar_serializer_cli
version: 2.1.23
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  analyzer: ^0.32.0
  build: ^0.12.7
  logging: ^0.11.3
  source_gen: ^0.8.3
  jaguar_serializer: ^2.1.12
  meta: ^1.1.5

dev_dependencies:
  test: ^1.2.0
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  collection: ^1.14.10
  path: ^1.6.1